select
    DESYNPUF_ID as desynpuf_id,
    cast(BENE_BIRTH_DT as date) as bene_birth_date,
    cast(BENE_DEATH_DT as date) as bene_death_date,
    BENE_SEX_IDENT_CD as bene_sex_ident_cd,
    BENE_RACE_CD as bene_race_cd,
    SP_STATE_CODE as state_code,
    cast(BENE_ESRD_IND as varchar) as bene_esrd_ind,
    cast(SP_ALZHDMTA as integer) as sp_alzhdmta,
    cast(SP_CHF as integer) as sp_chf,
    cast(SP_CHRNKIDN as integer) as sp_chrnkidn,
    cast(SP_CNCR as integer) as sp_cncr,
    cast(SP_COPD as integer) as sp_copd,
    cast(SP_DEPRESSN as integer) as sp_depressn,
    cast(SP_DIABETES as integer) as sp_diabetes,
    cast(SP_ISCHMCHT as integer) as sp_ischmcht,
    cast(SP_OSTEOPRS as integer) as sp_osteoprs,
    cast(SP_RA_OA as integer) as sp_ra_oa,
    cast(SP_STRKETIA as integer) as sp_strketia,
    cast(MEDREIMB_IP as number(18,2)) as medreimb_ip,
    cast(BENRES_IP as number(18,2)) as benres_ip,
    cast(PPPYMT_IP as number(18,2)) as pppymt_ip,
    cast(MEDREIMB_OP as number(18,2)) as medreimb_op,
    cast(BENRES_OP as number(18,2)) as benres_op,
    cast(PPPYMT_OP as number(18,2)) as pppymt_op,
    cast(MEDREIMB_CAR as number(18,2)) as medreimb_car,
    cast(BENRES_CAR as number(18,2)) as benres_car,
    cast(PPPYMT_CAR as number(18,2)) as pppymt_car,
    1 as sample_id,
    2009 as claim_year,
    'DE1_0_2009_BENEFICIARY_SUMMARY_FILE_SAMPLE_1' as source_table_name
from {{ source('synpuf_prestaging', 'DE1_0_2009_BENEFICIARY_SUMMARY_FILE_SAMPLE_1') }}
