{{ config(materialized='view') }}

select
    cast(DESYNPUF_ID as {{ type_string() }}) as desynpuf_id,
    {{ type_date('BENE_BIRTH_DT') }} as bene_birth_dt,
    {{ type_date('BENE_DEATH_DT') }} as bene_death_dt,
    cast(BENE_SEX_IDENT_CD as {{ type_string() }}) as bene_sex_ident_cd,
    cast(BENE_RACE_CD as {{ type_string() }}) as bene_race_cd,
    cast(BENE_ESRD_IND as {{ type_string() }}) as bene_esrd_ind,
    cast(SP_STATE_CODE as {{ type_string() }}) as sp_state_code,
    cast(BENE_COUNTY_CD as {{ type_string() }}) as bene_county_cd,
    cast(BENE_HI_CVRAGE_TOT_MONS as integer) as bene_hi_cvrage_tot_mons,
    cast(BENE_SMI_CVRAGE_TOT_MONS as integer) as bene_smi_cvrage_tot_mons,
    cast(BENE_HMO_CVRAGE_TOT_MONS as integer) as bene_hmo_cvrage_tot_mons,
    cast(PLAN_CVRG_MOS_NUM as {{ type_string() }}) as plan_cvrg_mos_num,
    cast(SP_ALZHDMTA as integer) as sp_alzhdmta,
    cast(SP_CHF as integer) as sp_chf,
    cast(SP_CHRNKIDN as integer) as sp_chrnkidn,
    cast(SP_CNCR as integer) as sp_cncr,
    cast(SP_COPD as integer) as sp_copd,
    cast(SP_DEPRESSN as integer) as sp_depressn,
    cast(SP_DIABETES as integer) as sp_diabetes,
    cast(SP_ISCHMCHT as integer) as sp_ischmcht,
    cast(SP_OSTEOPRS as integer) as sp_osteoprs,
    cast(SP_RA_OA as integer) as sp_ra_oa,
    cast(SP_STRKETIA as integer) as sp_strketia,
    cast(MEDREIMB_IP as {{ type_decimal(38, 2) }}) as medreimb_ip,
    cast(BENRES_IP as {{ type_decimal(38, 2) }}) as benres_ip,
    cast(PPPYMT_IP as {{ type_decimal(38, 2) }}) as pppymt_ip,
    cast(MEDREIMB_OP as {{ type_decimal(38, 2) }}) as medreimb_op,
    cast(BENRES_OP as {{ type_decimal(38, 2) }}) as benres_op,
    cast(PPPYMT_OP as {{ type_decimal(38, 2) }}) as pppymt_op,
    cast(MEDREIMB_CAR as {{ type_decimal(38, 2) }}) as medreimb_car,
    cast(BENRES_CAR as {{ type_decimal(38, 2) }}) as benres_car,
    cast(PPPYMT_CAR as {{ type_decimal(38, 2) }}) as pppymt_car,
    1 as sample_id,
    2009 as claim_year,
    'DE1_0_2009_BENEFICIARY_SUMMARY_FILE_SAMPLE_1' as source_table_name
from {{ source('synpuf_prestaging', 'DE1_0_2009_BENEFICIARY_SUMMARY_FILE_SAMPLE_1') }}
