select
    DESYNPUF_ID as desynpuf_id,
    CLM_ID as claim_id,
    cast(CLM_FROM_DT as date) as claim_from_date,
    cast(CLM_THRU_DT as date) as claim_thru_date,
    PRVDR_NUM as provider_number,
    CLM_PMT_AMT as claim_payment_amount,
    NCH_PRMRY_PYR_CLM_PD_AMT as nch_primary_payer_claim_paid_amount,
    AT_PHYSN_NPI as attending_physician_npi,
    OP_PHYSN_NPI as operating_physician_npi,
    OT_PHYSN_NPI as other_physician_npi,
    PRNCPAL_DGNS_CD as principal_diagnosis_code,
    ICD9_DGNS_CD_1 as diagnosis_code_1,
    ICD9_DGNS_CD_2 as diagnosis_code_2,
    ICD9_DGNS_CD_3 as diagnosis_code_3,
    ICD9_DGNS_CD_4 as diagnosis_code_4,
    ICD9_DGNS_CD_5 as diagnosis_code_5,
    ICD9_DGNS_CD_6 as diagnosis_code_6,
    ICD9_DGNS_CD_7 as diagnosis_code_7,
    ICD9_DGNS_CD_8 as diagnosis_code_8,
    ICD9_DGNS_CD_9 as diagnosis_code_9,
    ICD9_DGNS_CD_10 as diagnosis_code_10,
    1 as sample_id,
    'DE1_0_2008_TO_2010_OUTPATIENT_CLAIMS_SAMPLE_1' as source_table_name
from {{ source('synpuf_prestaging', 'DE1_0_2008_TO_2010_OUTPATIENT_CLAIMS_SAMPLE_1') }}
