{{ config(materialized='view') }}

select
    cast(DESYNPUF_ID as {{ type_string() }}) as desynpuf_id,
    cast(CLM_ID as {{ type_string() }}) as clm_id,
    {{ type_date('CLM_FROM_DT') }} as clm_from_dt,
    {{ type_date('CLM_THRU_DT') }} as clm_thru_dt,
    cast(ICD9_DGNS_CD_1 as {{ type_string() }}) as icd9_dgns_cd_1,
    cast(ICD9_DGNS_CD_2 as {{ type_string() }}) as icd9_dgns_cd_2,
    cast(ICD9_DGNS_CD_3 as {{ type_string() }}) as icd9_dgns_cd_3,
    cast(ICD9_DGNS_CD_4 as {{ type_string() }}) as icd9_dgns_cd_4,
    cast(ICD9_DGNS_CD_5 as {{ type_string() }}) as icd9_dgns_cd_5,
    cast(ICD9_DGNS_CD_6 as {{ type_string() }}) as icd9_dgns_cd_6,
    cast(ICD9_DGNS_CD_7 as {{ type_string() }}) as icd9_dgns_cd_7,
    cast(ICD9_DGNS_CD_8 as {{ type_string() }}) as icd9_dgns_cd_8,
    cast(PRF_PHYSN_NPI_1 as {{ type_string() }}) as prf_physn_npi_1,
    cast(PRF_PHYSN_NPI_2 as {{ type_string() }}) as prf_physn_npi_2,
    cast(PRF_PHYSN_NPI_3 as {{ type_string() }}) as prf_physn_npi_3,
    cast(PRF_PHYSN_NPI_4 as {{ type_string() }}) as prf_physn_npi_4,
    cast(PRF_PHYSN_NPI_5 as {{ type_string() }}) as prf_physn_npi_5,
    cast(PRF_PHYSN_NPI_6 as {{ type_string() }}) as prf_physn_npi_6,
    cast(PRF_PHYSN_NPI_7 as {{ type_string() }}) as prf_physn_npi_7,
    cast(PRF_PHYSN_NPI_8 as {{ type_string() }}) as prf_physn_npi_8,
    cast(PRF_PHYSN_NPI_9 as {{ type_string() }}) as prf_physn_npi_9,
    cast(PRF_PHYSN_NPI_10 as {{ type_string() }}) as prf_physn_npi_10,
    cast(PRF_PHYSN_NPI_11 as {{ type_string() }}) as prf_physn_npi_11,
    cast(PRF_PHYSN_NPI_12 as {{ type_string() }}) as prf_physn_npi_12,
    cast(PRF_PHYSN_NPI_13 as {{ type_string() }}) as prf_physn_npi_13,
    cast(TAX_NUM_1 as {{ type_string() }}) as tax_num_1,
    cast(TAX_NUM_2 as {{ type_string() }}) as tax_num_2,
    cast(TAX_NUM_3 as {{ type_string() }}) as tax_num_3,
    cast(TAX_NUM_4 as {{ type_string() }}) as tax_num_4,
    cast(TAX_NUM_5 as {{ type_string() }}) as tax_num_5,
    cast(TAX_NUM_6 as {{ type_string() }}) as tax_num_6,
    cast(TAX_NUM_7 as {{ type_string() }}) as tax_num_7,
    cast(TAX_NUM_8 as {{ type_string() }}) as tax_num_8,
    cast(TAX_NUM_9 as {{ type_string() }}) as tax_num_9,
    cast(TAX_NUM_10 as {{ type_string() }}) as tax_num_10,
    cast(TAX_NUM_11 as {{ type_string() }}) as tax_num_11,
    cast(TAX_NUM_12 as {{ type_string() }}) as tax_num_12,
    cast(TAX_NUM_13 as {{ type_string() }}) as tax_num_13,
    cast(HCPCS_CD_1 as {{ type_string() }}) as hcpcs_cd_1,
    cast(HCPCS_CD_2 as {{ type_string() }}) as hcpcs_cd_2,
    cast(HCPCS_CD_3 as {{ type_string() }}) as hcpcs_cd_3,
    cast(HCPCS_CD_4 as {{ type_string() }}) as hcpcs_cd_4,
    cast(HCPCS_CD_5 as {{ type_string() }}) as hcpcs_cd_5,
    cast(HCPCS_CD_6 as {{ type_string() }}) as hcpcs_cd_6,
    cast(HCPCS_CD_7 as {{ type_string() }}) as hcpcs_cd_7,
    cast(HCPCS_CD_8 as {{ type_string() }}) as hcpcs_cd_8,
    cast(HCPCS_CD_9 as {{ type_string() }}) as hcpcs_cd_9,
    cast(HCPCS_CD_10 as {{ type_string() }}) as hcpcs_cd_10,
    cast(HCPCS_CD_11 as {{ type_string() }}) as hcpcs_cd_11,
    cast(HCPCS_CD_12 as {{ type_string() }}) as hcpcs_cd_12,
    cast(HCPCS_CD_13 as {{ type_string() }}) as hcpcs_cd_13,
    cast(LINE_NCH_PMT_AMT_1 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_1,
    cast(LINE_NCH_PMT_AMT_2 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_2,
    cast(LINE_NCH_PMT_AMT_3 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_3,
    cast(LINE_NCH_PMT_AMT_4 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_4,
    cast(LINE_NCH_PMT_AMT_5 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_5,
    cast(LINE_NCH_PMT_AMT_6 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_6,
    cast(LINE_NCH_PMT_AMT_7 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_7,
    cast(LINE_NCH_PMT_AMT_8 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_8,
    cast(LINE_NCH_PMT_AMT_9 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_9,
    cast(LINE_NCH_PMT_AMT_10 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_10,
    cast(LINE_NCH_PMT_AMT_11 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_11,
    cast(LINE_NCH_PMT_AMT_12 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_12,
    cast(LINE_NCH_PMT_AMT_13 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_13,
    cast(LINE_BENE_PTB_DDCTBL_AMT_1 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_1,
    cast(LINE_BENE_PTB_DDCTBL_AMT_2 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_2,
    cast(LINE_BENE_PTB_DDCTBL_AMT_3 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_3,
    cast(LINE_BENE_PTB_DDCTBL_AMT_4 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_4,
    cast(LINE_BENE_PTB_DDCTBL_AMT_5 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_5,
    cast(LINE_BENE_PTB_DDCTBL_AMT_6 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_6,
    cast(LINE_BENE_PTB_DDCTBL_AMT_7 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_7,
    cast(LINE_BENE_PTB_DDCTBL_AMT_8 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_8,
    cast(LINE_BENE_PTB_DDCTBL_AMT_9 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_9,
    cast(LINE_BENE_PTB_DDCTBL_AMT_10 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_10,
    cast(LINE_BENE_PTB_DDCTBL_AMT_11 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_11,
    cast(LINE_BENE_PTB_DDCTBL_AMT_12 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_12,
    cast(LINE_BENE_PTB_DDCTBL_AMT_13 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_13,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_1 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_1,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_2 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_2,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_3 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_3,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_4 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_4,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_5 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_5,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_6 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_6,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_7 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_7,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_8 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_8,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_9 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_9,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_10 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_10,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_11 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_11,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_12 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_12,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_13 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_13,
    cast(LINE_COINSRNC_AMT_1 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_1,
    cast(LINE_COINSRNC_AMT_2 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_2,
    cast(LINE_COINSRNC_AMT_3 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_3,
    cast(LINE_COINSRNC_AMT_4 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_4,
    cast(LINE_COINSRNC_AMT_5 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_5,
    cast(LINE_COINSRNC_AMT_6 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_6,
    cast(LINE_COINSRNC_AMT_7 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_7,
    cast(LINE_COINSRNC_AMT_8 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_8,
    cast(LINE_COINSRNC_AMT_9 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_9,
    cast(LINE_COINSRNC_AMT_10 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_10,
    cast(LINE_COINSRNC_AMT_11 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_11,
    cast(LINE_COINSRNC_AMT_12 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_12,
    cast(LINE_COINSRNC_AMT_13 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_13,
    cast(LINE_ALOWD_CHRG_AMT_1 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_1,
    cast(LINE_ALOWD_CHRG_AMT_2 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_2,
    cast(LINE_ALOWD_CHRG_AMT_3 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_3,
    cast(LINE_ALOWD_CHRG_AMT_4 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_4,
    cast(LINE_ALOWD_CHRG_AMT_5 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_5,
    cast(LINE_ALOWD_CHRG_AMT_6 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_6,
    cast(LINE_ALOWD_CHRG_AMT_7 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_7,
    cast(LINE_ALOWD_CHRG_AMT_8 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_8,
    cast(LINE_ALOWD_CHRG_AMT_9 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_9,
    cast(LINE_ALOWD_CHRG_AMT_10 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_10,
    cast(LINE_ALOWD_CHRG_AMT_11 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_11,
    cast(LINE_ALOWD_CHRG_AMT_12 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_12,
    cast(LINE_ALOWD_CHRG_AMT_13 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_13,
    cast(LINE_PRCSG_IND_CD_1 as {{ type_string() }}) as line_prcsg_ind_cd_1,
    cast(LINE_PRCSG_IND_CD_2 as {{ type_string() }}) as line_prcsg_ind_cd_2,
    cast(LINE_PRCSG_IND_CD_3 as {{ type_string() }}) as line_prcsg_ind_cd_3,
    cast(LINE_PRCSG_IND_CD_4 as {{ type_string() }}) as line_prcsg_ind_cd_4,
    cast(LINE_PRCSG_IND_CD_5 as {{ type_string() }}) as line_prcsg_ind_cd_5,
    cast(LINE_PRCSG_IND_CD_6 as {{ type_string() }}) as line_prcsg_ind_cd_6,
    cast(LINE_PRCSG_IND_CD_7 as {{ type_string() }}) as line_prcsg_ind_cd_7,
    cast(LINE_PRCSG_IND_CD_8 as {{ type_string() }}) as line_prcsg_ind_cd_8,
    cast(LINE_PRCSG_IND_CD_9 as {{ type_string() }}) as line_prcsg_ind_cd_9,
    cast(LINE_PRCSG_IND_CD_10 as {{ type_string() }}) as line_prcsg_ind_cd_10,
    cast(LINE_PRCSG_IND_CD_11 as {{ type_string() }}) as line_prcsg_ind_cd_11,
    cast(LINE_PRCSG_IND_CD_12 as {{ type_string() }}) as line_prcsg_ind_cd_12,
    cast(LINE_PRCSG_IND_CD_13 as {{ type_string() }}) as line_prcsg_ind_cd_13,
    cast(LINE_ICD9_DGNS_CD_1 as {{ type_string() }}) as line_icd9_dgns_cd_1,
    cast(LINE_ICD9_DGNS_CD_2 as {{ type_string() }}) as line_icd9_dgns_cd_2,
    cast(LINE_ICD9_DGNS_CD_3 as {{ type_string() }}) as line_icd9_dgns_cd_3,
    cast(LINE_ICD9_DGNS_CD_4 as {{ type_string() }}) as line_icd9_dgns_cd_4,
    cast(LINE_ICD9_DGNS_CD_5 as {{ type_string() }}) as line_icd9_dgns_cd_5,
    cast(LINE_ICD9_DGNS_CD_6 as {{ type_string() }}) as line_icd9_dgns_cd_6,
    cast(LINE_ICD9_DGNS_CD_7 as {{ type_string() }}) as line_icd9_dgns_cd_7,
    cast(LINE_ICD9_DGNS_CD_8 as {{ type_string() }}) as line_icd9_dgns_cd_8,
    cast(LINE_ICD9_DGNS_CD_9 as {{ type_string() }}) as line_icd9_dgns_cd_9,
    cast(LINE_ICD9_DGNS_CD_10 as {{ type_string() }}) as line_icd9_dgns_cd_10,
    cast(LINE_ICD9_DGNS_CD_11 as {{ type_string() }}) as line_icd9_dgns_cd_11,
    cast(LINE_ICD9_DGNS_CD_12 as {{ type_string() }}) as line_icd9_dgns_cd_12,
    cast(LINE_ICD9_DGNS_CD_13 as {{ type_string() }}) as line_icd9_dgns_cd_13,
    1 as sample_id,
    'DE1_0_2008_TO_2010_CARRIER_CLAIMS_SAMPLE_1A' as source_table_name
from {{ source('synpuf_prestaging', 'DE1_0_2008_TO_2010_CARRIER_CLAIMS_SAMPLE_1A') }}
union all
select
    cast(DESYNPUF_ID as {{ type_string() }}) as desynpuf_id,
    cast(CLM_ID as {{ type_string() }}) as clm_id,
    {{ type_date('CLM_FROM_DT') }} as clm_from_dt,
    {{ type_date('CLM_THRU_DT') }} as clm_thru_dt,
    cast(ICD9_DGNS_CD_1 as {{ type_string() }}) as icd9_dgns_cd_1,
    cast(ICD9_DGNS_CD_2 as {{ type_string() }}) as icd9_dgns_cd_2,
    cast(ICD9_DGNS_CD_3 as {{ type_string() }}) as icd9_dgns_cd_3,
    cast(ICD9_DGNS_CD_4 as {{ type_string() }}) as icd9_dgns_cd_4,
    cast(ICD9_DGNS_CD_5 as {{ type_string() }}) as icd9_dgns_cd_5,
    cast(ICD9_DGNS_CD_6 as {{ type_string() }}) as icd9_dgns_cd_6,
    cast(ICD9_DGNS_CD_7 as {{ type_string() }}) as icd9_dgns_cd_7,
    cast(ICD9_DGNS_CD_8 as {{ type_string() }}) as icd9_dgns_cd_8,
    cast(PRF_PHYSN_NPI_1 as {{ type_string() }}) as prf_physn_npi_1,
    cast(PRF_PHYSN_NPI_2 as {{ type_string() }}) as prf_physn_npi_2,
    cast(PRF_PHYSN_NPI_3 as {{ type_string() }}) as prf_physn_npi_3,
    cast(PRF_PHYSN_NPI_4 as {{ type_string() }}) as prf_physn_npi_4,
    cast(PRF_PHYSN_NPI_5 as {{ type_string() }}) as prf_physn_npi_5,
    cast(PRF_PHYSN_NPI_6 as {{ type_string() }}) as prf_physn_npi_6,
    cast(PRF_PHYSN_NPI_7 as {{ type_string() }}) as prf_physn_npi_7,
    cast(PRF_PHYSN_NPI_8 as {{ type_string() }}) as prf_physn_npi_8,
    cast(PRF_PHYSN_NPI_9 as {{ type_string() }}) as prf_physn_npi_9,
    cast(PRF_PHYSN_NPI_10 as {{ type_string() }}) as prf_physn_npi_10,
    cast(PRF_PHYSN_NPI_11 as {{ type_string() }}) as prf_physn_npi_11,
    cast(PRF_PHYSN_NPI_12 as {{ type_string() }}) as prf_physn_npi_12,
    cast(PRF_PHYSN_NPI_13 as {{ type_string() }}) as prf_physn_npi_13,
    cast(TAX_NUM_1 as {{ type_string() }}) as tax_num_1,
    cast(TAX_NUM_2 as {{ type_string() }}) as tax_num_2,
    cast(TAX_NUM_3 as {{ type_string() }}) as tax_num_3,
    cast(TAX_NUM_4 as {{ type_string() }}) as tax_num_4,
    cast(TAX_NUM_5 as {{ type_string() }}) as tax_num_5,
    cast(TAX_NUM_6 as {{ type_string() }}) as tax_num_6,
    cast(TAX_NUM_7 as {{ type_string() }}) as tax_num_7,
    cast(TAX_NUM_8 as {{ type_string() }}) as tax_num_8,
    cast(TAX_NUM_9 as {{ type_string() }}) as tax_num_9,
    cast(TAX_NUM_10 as {{ type_string() }}) as tax_num_10,
    cast(TAX_NUM_11 as {{ type_string() }}) as tax_num_11,
    cast(TAX_NUM_12 as {{ type_string() }}) as tax_num_12,
    cast(TAX_NUM_13 as {{ type_string() }}) as tax_num_13,
    cast(HCPCS_CD_1 as {{ type_string() }}) as hcpcs_cd_1,
    cast(HCPCS_CD_2 as {{ type_string() }}) as hcpcs_cd_2,
    cast(HCPCS_CD_3 as {{ type_string() }}) as hcpcs_cd_3,
    cast(HCPCS_CD_4 as {{ type_string() }}) as hcpcs_cd_4,
    cast(HCPCS_CD_5 as {{ type_string() }}) as hcpcs_cd_5,
    cast(HCPCS_CD_6 as {{ type_string() }}) as hcpcs_cd_6,
    cast(HCPCS_CD_7 as {{ type_string() }}) as hcpcs_cd_7,
    cast(HCPCS_CD_8 as {{ type_string() }}) as hcpcs_cd_8,
    cast(HCPCS_CD_9 as {{ type_string() }}) as hcpcs_cd_9,
    cast(HCPCS_CD_10 as {{ type_string() }}) as hcpcs_cd_10,
    cast(HCPCS_CD_11 as {{ type_string() }}) as hcpcs_cd_11,
    cast(HCPCS_CD_12 as {{ type_string() }}) as hcpcs_cd_12,
    cast(HCPCS_CD_13 as {{ type_string() }}) as hcpcs_cd_13,
    cast(LINE_NCH_PMT_AMT_1 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_1,
    cast(LINE_NCH_PMT_AMT_2 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_2,
    cast(LINE_NCH_PMT_AMT_3 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_3,
    cast(LINE_NCH_PMT_AMT_4 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_4,
    cast(LINE_NCH_PMT_AMT_5 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_5,
    cast(LINE_NCH_PMT_AMT_6 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_6,
    cast(LINE_NCH_PMT_AMT_7 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_7,
    cast(LINE_NCH_PMT_AMT_8 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_8,
    cast(LINE_NCH_PMT_AMT_9 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_9,
    cast(LINE_NCH_PMT_AMT_10 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_10,
    cast(LINE_NCH_PMT_AMT_11 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_11,
    cast(LINE_NCH_PMT_AMT_12 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_12,
    cast(LINE_NCH_PMT_AMT_13 as {{ type_decimal(38, 2) }}) as line_nch_pmt_amt_13,
    cast(LINE_BENE_PTB_DDCTBL_AMT_1 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_1,
    cast(LINE_BENE_PTB_DDCTBL_AMT_2 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_2,
    cast(LINE_BENE_PTB_DDCTBL_AMT_3 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_3,
    cast(LINE_BENE_PTB_DDCTBL_AMT_4 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_4,
    cast(LINE_BENE_PTB_DDCTBL_AMT_5 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_5,
    cast(LINE_BENE_PTB_DDCTBL_AMT_6 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_6,
    cast(LINE_BENE_PTB_DDCTBL_AMT_7 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_7,
    cast(LINE_BENE_PTB_DDCTBL_AMT_8 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_8,
    cast(LINE_BENE_PTB_DDCTBL_AMT_9 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_9,
    cast(LINE_BENE_PTB_DDCTBL_AMT_10 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_10,
    cast(LINE_BENE_PTB_DDCTBL_AMT_11 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_11,
    cast(LINE_BENE_PTB_DDCTBL_AMT_12 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_12,
    cast(LINE_BENE_PTB_DDCTBL_AMT_13 as {{ type_decimal(38, 2) }}) as line_bene_ptb_ddctbl_amt_13,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_1 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_1,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_2 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_2,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_3 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_3,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_4 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_4,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_5 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_5,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_6 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_6,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_7 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_7,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_8 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_8,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_9 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_9,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_10 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_10,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_11 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_11,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_12 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_12,
    cast(LINE_BENE_PRMRY_PYR_PD_AMT_13 as {{ type_decimal(38, 2) }}) as line_bene_prmry_pyr_pd_amt_13,
    cast(LINE_COINSRNC_AMT_1 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_1,
    cast(LINE_COINSRNC_AMT_2 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_2,
    cast(LINE_COINSRNC_AMT_3 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_3,
    cast(LINE_COINSRNC_AMT_4 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_4,
    cast(LINE_COINSRNC_AMT_5 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_5,
    cast(LINE_COINSRNC_AMT_6 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_6,
    cast(LINE_COINSRNC_AMT_7 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_7,
    cast(LINE_COINSRNC_AMT_8 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_8,
    cast(LINE_COINSRNC_AMT_9 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_9,
    cast(LINE_COINSRNC_AMT_10 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_10,
    cast(LINE_COINSRNC_AMT_11 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_11,
    cast(LINE_COINSRNC_AMT_12 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_12,
    cast(LINE_COINSRNC_AMT_13 as {{ type_decimal(38, 2) }}) as line_coinsrnc_amt_13,
    cast(LINE_ALOWD_CHRG_AMT_1 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_1,
    cast(LINE_ALOWD_CHRG_AMT_2 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_2,
    cast(LINE_ALOWD_CHRG_AMT_3 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_3,
    cast(LINE_ALOWD_CHRG_AMT_4 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_4,
    cast(LINE_ALOWD_CHRG_AMT_5 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_5,
    cast(LINE_ALOWD_CHRG_AMT_6 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_6,
    cast(LINE_ALOWD_CHRG_AMT_7 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_7,
    cast(LINE_ALOWD_CHRG_AMT_8 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_8,
    cast(LINE_ALOWD_CHRG_AMT_9 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_9,
    cast(LINE_ALOWD_CHRG_AMT_10 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_10,
    cast(LINE_ALOWD_CHRG_AMT_11 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_11,
    cast(LINE_ALOWD_CHRG_AMT_12 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_12,
    cast(LINE_ALOWD_CHRG_AMT_13 as {{ type_decimal(38, 2) }}) as line_alowd_chrg_amt_13,
    cast(LINE_PRCSG_IND_CD_1 as {{ type_string() }}) as line_prcsg_ind_cd_1,
    cast(LINE_PRCSG_IND_CD_2 as {{ type_string() }}) as line_prcsg_ind_cd_2,
    cast(LINE_PRCSG_IND_CD_3 as {{ type_string() }}) as line_prcsg_ind_cd_3,
    cast(LINE_PRCSG_IND_CD_4 as {{ type_string() }}) as line_prcsg_ind_cd_4,
    cast(LINE_PRCSG_IND_CD_5 as {{ type_string() }}) as line_prcsg_ind_cd_5,
    cast(LINE_PRCSG_IND_CD_6 as {{ type_string() }}) as line_prcsg_ind_cd_6,
    cast(LINE_PRCSG_IND_CD_7 as {{ type_string() }}) as line_prcsg_ind_cd_7,
    cast(LINE_PRCSG_IND_CD_8 as {{ type_string() }}) as line_prcsg_ind_cd_8,
    cast(LINE_PRCSG_IND_CD_9 as {{ type_string() }}) as line_prcsg_ind_cd_9,
    cast(LINE_PRCSG_IND_CD_10 as {{ type_string() }}) as line_prcsg_ind_cd_10,
    cast(LINE_PRCSG_IND_CD_11 as {{ type_string() }}) as line_prcsg_ind_cd_11,
    cast(LINE_PRCSG_IND_CD_12 as {{ type_string() }}) as line_prcsg_ind_cd_12,
    cast(LINE_PRCSG_IND_CD_13 as {{ type_string() }}) as line_prcsg_ind_cd_13,
    cast(LINE_ICD9_DGNS_CD_1 as {{ type_string() }}) as line_icd9_dgns_cd_1,
    cast(LINE_ICD9_DGNS_CD_2 as {{ type_string() }}) as line_icd9_dgns_cd_2,
    cast(LINE_ICD9_DGNS_CD_3 as {{ type_string() }}) as line_icd9_dgns_cd_3,
    cast(LINE_ICD9_DGNS_CD_4 as {{ type_string() }}) as line_icd9_dgns_cd_4,
    cast(LINE_ICD9_DGNS_CD_5 as {{ type_string() }}) as line_icd9_dgns_cd_5,
    cast(LINE_ICD9_DGNS_CD_6 as {{ type_string() }}) as line_icd9_dgns_cd_6,
    cast(LINE_ICD9_DGNS_CD_7 as {{ type_string() }}) as line_icd9_dgns_cd_7,
    cast(LINE_ICD9_DGNS_CD_8 as {{ type_string() }}) as line_icd9_dgns_cd_8,
    cast(LINE_ICD9_DGNS_CD_9 as {{ type_string() }}) as line_icd9_dgns_cd_9,
    cast(LINE_ICD9_DGNS_CD_10 as {{ type_string() }}) as line_icd9_dgns_cd_10,
    cast(LINE_ICD9_DGNS_CD_11 as {{ type_string() }}) as line_icd9_dgns_cd_11,
    cast(LINE_ICD9_DGNS_CD_12 as {{ type_string() }}) as line_icd9_dgns_cd_12,
    cast(LINE_ICD9_DGNS_CD_13 as {{ type_string() }}) as line_icd9_dgns_cd_13,
    1 as sample_id,
    'DE1_0_2008_TO_2010_CARRIER_CLAIMS_SAMPLE_1B' as source_table_name
from {{ source('synpuf_prestaging', 'DE1_0_2008_TO_2010_CARRIER_CLAIMS_SAMPLE_1B') }}
